{% set name = "sagetex" %}
{% set version = "3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sagemath/sagetex/releases/download/v{{ version }}/sagetex-{{ version }}.tar.gz
  sha256: 26df48534bb22c89874e7afd2ae211568c5a324c651eb2ac0c18580370de93f5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  # Can't import sagetex without sage and sagetex is a dependency of sage
  commands:
    - test -f $PREFIX/share/texmf/tex/latex/sagetex/sagetex.sty  # [unix]

about:
  home: http://github.com/sagemath/sagetex
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Embed code, results of computations, and plots from the Sage mathematics software suite into LaTeX documents

extra:
  recipe-maintainers:
    - conda-forge/sage
